// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iphem_web.Models;

#nullable disable

namespace iphem_web.Migrations
{
    [DbContext(typeof(IphemDbContext))]
    [Migration("20260318013055_AgregarTablaTriage")]
    partial class AgregarTablaTriage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iphem_web.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValoresAntiguos")
                        .HasColumnType("text");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("iphem_web.Models.Carrusel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Enlace")
                        .HasColumnType("text")
                        .HasColumnName("enlace");

                    b.Property<string>("ImagenPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagenpath");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("text")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("carrusel");
                });

            modelBuilder.Entity("iphem_web.Models.ConfiguracionTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadTurnos")
                        .HasColumnType("integer")
                        .HasColumnName("cantidadturnos");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("horainicio");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("intervalominutos");

                    b.HasKey("Id");

                    b.ToTable("configuracionturnos");
                });

            modelBuilder.Entity("iphem_web.Models.Estadosturno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("estadosturno_pkey");

                    b.ToTable("estadosturno", (string)null);
                });

            modelBuilder.Entity("iphem_web.Models.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Epigrafe")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("epigrafe");

                    b.Property<DateTime?>("Fechapublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechapublicacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Idusuariocreador")
                        .HasColumnType("integer")
                        .HasColumnName("idusuariocreador");

                    b.Property<string>("ImagenPath")
                        .HasColumnType("text")
                        .HasColumnName("imagenpath");

                    b.Property<string>("Imagenurl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imagenurl");

                    b.Property<string>("Piedefoto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("piedefoto");

                    b.Property<string>("Subtitulo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("noticias_pkey");

                    b.HasIndex("Idusuariocreador");

                    b.ToTable("noticias", (string)null);
                });

            modelBuilder.Entity("iphem_web.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Nombre" }, "roles_nombre_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("iphem_web.Models.Tiposturno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("tiposturno_pkey");

                    b.ToTable("tiposturno", (string)null);
                });

            modelBuilder.Entity("iphem_web.Models.Triage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptoDeclaracionJurada")
                        .HasColumnType("boolean");

                    b.Property<bool>("Cirugias12Meses")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmbarazoOLactancia")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdTurno")
                        .HasColumnType("integer");

                    b.Property<bool>("PesoMayor50Kg")
                        .HasColumnType("boolean");

                    b.Property<bool>("SentirseBienHoy")
                        .HasColumnType("boolean");

                    b.Property<bool>("TatuajesPiercings12Meses")
                        .HasColumnType("boolean");

                    b.Property<bool>("TomoAntibioticos7Dias")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdTurno")
                        .IsUnique();

                    b.ToTable("Triages");
                });

            modelBuilder.Entity("iphem_web.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidosolicitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidosolicitante");

                    b.Property<string>("Departamento")
                        .HasColumnType("text")
                        .HasColumnName("departamento");

                    b.Property<string>("Dnisolicitante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dnisolicitante");

                    b.Property<string>("Emailsolicitante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emailsolicitante");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Fechahora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechahora");

                    b.Property<string>("GrupoSanguineo")
                        .HasColumnType("text")
                        .HasColumnName("gruposanguineo");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("Idestadoturno")
                        .HasColumnType("integer")
                        .HasColumnName("idestadoturno");

                    b.Property<int>("Idtipoturno")
                        .HasColumnType("integer")
                        .HasColumnName("idtipoturno");

                    b.Property<string>("Nombresolicitante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombresolicitante");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Pacientedestino")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pacientedestino");

                    b.Property<string>("Telefonosolicitante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefonosolicitante");

                    b.HasKey("Id")
                        .HasName("turnos_pkey");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Idestadoturno");

                    b.HasIndex("Idtipoturno");

                    b.ToTable("turnos", (string)null);
                });

            modelBuilder.Entity("iphem_web.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Fechaalta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechaalta")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Idrol")
                        .HasColumnType("integer")
                        .HasColumnName("idrol");

                    b.Property<string>("Nombrecompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombrecompleto");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash");

                    b.HasKey("Id")
                        .HasName("usuarios_pkey");

                    b.HasIndex("Idrol");

                    b.HasIndex(new[] { "Email" }, "usuarios_email_key")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("iphem_web.Models.Noticia", b =>
                {
                    b.HasOne("iphem_web.Models.Usuario", "IdusuariocreadorNavigation")
                        .WithMany("Noticia")
                        .HasForeignKey("Idusuariocreador")
                        .HasConstraintName("noticias_idusuariocreador_fkey");

                    b.Navigation("IdusuariocreadorNavigation");
                });

            modelBuilder.Entity("iphem_web.Models.Triage", b =>
                {
                    b.HasOne("iphem_web.Models.Turno", "TurnoNavigation")
                        .WithOne("TriageNavigation")
                        .HasForeignKey("iphem_web.Models.Triage", "IdTurno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TurnoNavigation");
                });

            modelBuilder.Entity("iphem_web.Models.Turno", b =>
                {
                    b.HasOne("iphem_web.Models.Usuario", "UsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.HasOne("iphem_web.Models.Estadosturno", "IdestadoturnoNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("Idestadoturno")
                        .IsRequired()
                        .HasConstraintName("turnos_idestadoturno_fkey");

                    b.HasOne("iphem_web.Models.Tiposturno", "IdtipoturnoNavigation")
                        .WithMany("Turnos")
                        .HasForeignKey("Idtipoturno")
                        .IsRequired()
                        .HasConstraintName("turnos_idtipoturno_fkey");

                    b.Navigation("IdestadoturnoNavigation");

                    b.Navigation("IdtipoturnoNavigation");

                    b.Navigation("UsuarioNavigation");
                });

            modelBuilder.Entity("iphem_web.Models.Usuario", b =>
                {
                    b.HasOne("iphem_web.Models.Role", "IdrolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Idrol")
                        .IsRequired()
                        .HasConstraintName("usuarios_idrol_fkey");

                    b.Navigation("IdrolNavigation");
                });

            modelBuilder.Entity("iphem_web.Models.Estadosturno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("iphem_web.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("iphem_web.Models.Tiposturno", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("iphem_web.Models.Turno", b =>
                {
                    b.Navigation("TriageNavigation");
                });

            modelBuilder.Entity("iphem_web.Models.Usuario", b =>
                {
                    b.Navigation("Noticia");
                });
#pragma warning restore 612, 618
        }
    }
}
